#!/bin/bash
set -Eeuo pipefail

cleanup() {
    RC="$?"
    trap - ERR TERM HUP INT QUIT EXIT
    rm "${TMP_DIR}"/*-Packages 2>/dev/null || true
    if [ "${RC}" = "0" ]; then
        rm "${TMP_DIR}/pool-Args" 2>/dev/null || true
        rm "${TMP_DIR}/find-Sizes" 2>/dev/null || true
        mv "${TMP_DIR}/pool-MD5sums" "${MIRROR_DIR}/MD5SUMS" 2>/dev/null || true
    fi
    exit "${RC}"
}

test_req()
{
    reqs=(rm mkdir curl gunzip paste awk parallel touch sort uniq head cut tr wc)
    for req in "${reqs[@]}"; do
        if ! which "${req}" &>/dev/null; then echo "${req}" not installed 1>&2; exit 1; fi
    done
    if ! readarray < /dev/null; then
        echo "bash does not support readarray" 1>&2; exit 1
    fi
    if [ $(awk -V | head -1 | cut -d' ' -f1) != "GNU" ]; then
        echo "awk is not GNU awk" 1>&2; exit 1
    fi
}

include()
{
    if [ -f mirrorly.conf ]; then
        . mirrorly.conf
    elif [ -f /etc/mirrorly.conf ]; then
        . /etc/mirrorly.conf
    else
        echo "can't find mirrorly.conf in ${PWD} or /etc" 2>&1
    fi
}

setup_dirs()
{
    mkdir -p "${TMP_DIR}" || exit 2
    mkdir -p "${MIRROR_DIR}" || exit 2
    touch "${MIRROR_DIR}/testfile" 2>/dev/null || (echo cannot write to "${MIRROR_DIR}" 1>&2; exit 2) && rm "${MIRROR_DIR}/testfile"
}

usage()
{
    echo "Usage: ${0} [-h] this help message
                  [-1] only run stage 1
                  [-2] only run stage 2
                  [-c] check MD5sums of all files"
    trap - ERR TERM HUP INT QUIT EXIT
    exit 0
}

get_mirrors_from_list()
{
    readarray -t MIRROR_LIST < "${MIRROR_LIST_FILE}"
    MIRROR_LIST_LEN="${#MIRROR_LIST[@]}"
    local LIST_DISTROS=()
    for MIRROR in "${MIRROR_LIST[@]}"; do
        local CURRENT_MIRROR=(${MIRROR})
        local CURRENT_MIRROR_DISTRO="${CURRENT_MIRROR[1]##*\/}"
        LIST_DISTROS+=(${CURRENT_MIRROR_DISTRO})
    done
    DISTROS=($(for DISTRO in "${LIST_DISTROS[@]}"; do echo "${DISTRO}"; done | sort -u))
}

get_package_file_list()
{
    local i
    for (( i=0; i<$MIRROR_LIST_LEN; i++ )); do
        local CURRENT_MIRROR=(${MIRROR_LIST[$i]})
        local CURRENT_MIRROR_LEN="${#CURRENT_MIRROR[@]}"
        local CURRENT_MIRROR_DISTRO="${CURRENT_MIRROR[1]##*\/}"
        if [ "${CURRENT_MIRROR[0]}" != "deb" ]; then
            echo ERROR in "${CURRENT_MIRROR[@]}" 1>&2
            exit 3
        else
            echo -n "  ${CURRENT_MIRROR[1]} ${CURRENT_MIRROR[2]} "
        fi
        PACKAGE_FILES=()
        local j
        for (( j=3; j<"${CURRENT_MIRROR_LEN}"; j++ )); do
            CURRENT_MIRROR_J_TR=$(echo "${CURRENT_MIRROR[$j]}" | tr '/' '-')
            CURRENT_MIRROR_PACKAGE_FILE="${CURRENT_MIRROR_DISTRO}-${CURRENT_MIRROR[2]}-${CURRENT_MIRROR_J_TR}-Packages"
            echo -n "${CURRENT_MIRROR[$j]} "
            curl -fsSL "${CURRENT_MIRROR[1]}/dists/${CURRENT_MIRROR[2]}/${CURRENT_MIRROR[$j]}/binary-${ARCH}/Packages.gz" | gunzip > "${TMP_DIR}/${CURRENT_MIRROR_PACKAGE_FILE}"
            PACKAGE_FILES+=("${CURRENT_MIRROR_PACKAGE_FILE}")
        done
        echo
        for PACKAGE_FILENAME in "${PACKAGE_FILES[@]}"; do
            paste <(awk '/^Size. /{print $2}' "${TMP_DIR}/${PACKAGE_FILENAME}") <(awk -v url="${CURRENT_MIRROR[1]}" -v distro="${CURRENT_MIRROR_DISTRO}" '/^Filename. /{print url"\t"distro"\t"$2}' "${TMP_DIR}/${PACKAGE_FILENAME}") >> "${TMP_DIR}/pool-TMP"
            paste <(awk '/^MD5sum. /{print $2}' "${TMP_DIR}/${PACKAGE_FILENAME}") <(awk -v distro="${CURRENT_MIRROR_DISTRO}" '/^Filename. /{print distro"/"$2}' "${TMP_DIR}/${PACKAGE_FILENAME}") >> "${TMP_DIR}/pool-MD5sums"
        done
    done
    sort "${TMP_DIR}/pool-TMP" | uniq > "${TMP_DIR}/pool-Args" && rm "${TMP_DIR}/pool-TMP"
}

get_local_file_list()
{
    for DISTRO in "${DISTROS[@]}"; do
        echo "  ${MIRROR_DIR}/${DISTRO}"
        if [ -d "${MIRROR_DIR}/${DISTRO}/pool" ]; then
            (cd "${MIRROR_DIR}" && find "${DISTRO}/pool" -type f -ls | awk '{print $7"\t"$11}' >> "${TMP_DIR}/find-TMP")
        else
            touch "${TMP_DIR}/find-TMP"
        fi
    done
    sort "${TMP_DIR}/find-TMP" | uniq > "${TMP_DIR}/find-Sizes" && rm "${TMP_DIR}/find-TMP"
}

get_file_from_repo()
{
    local SIZE="${1}"
    local MIRROR="${2}"
    local DISTRO="${3}"
    local FILENAME="${4}"
    local OUTPUT="${MIRROR_DIR}/${DISTRO}/${FILENAME}"
    local URL="${MIRROR}/${FILENAME}"
    if [ ! -f "${OUTPUT}" ]; then
        curl -fsSL --create-dirs -o "${OUTPUT}" "${URL}"
    fi
    local STAT=$(stat -c %s "${OUTPUT}" 2>/dev/null || echo "0")
    if [ "${STAT}" -ne "${SIZE}" ]; then
        echo -n "SIZE NOT MATCHED: " 1>&2
        basename "${FILENAME}" 1>&2
        rm "${OUTPUT}"
        return 1
    else
        return 0
    fi
}

get_release_files()
{
    local i
    for (( i=0; i<$MIRROR_LIST_LEN; i++ )); do
        local CURRENT_MIRROR=(${MIRROR_LIST[$i]})
        local CURRENT_MIRROR_LEN="${#CURRENT_MIRROR[@]}"
        local CURRENT_MIRROR_DISTRO="${CURRENT_MIRROR[1]##*\/}"
        local RELEASE_FILES=(InRelease Release Release.gpg)
        echo -n "  ${CURRENT_MIRROR[1]} ${CURRENT_MIRROR[2]} "
        for FILE in "${RELEASE_FILES[@]}"; do
            local URL="${CURRENT_MIRROR[1]}/dists/${CURRENT_MIRROR[2]}/${FILE}"
            local OUTPUT="${MIRROR_DIR}/${CURRENT_MIRROR_DISTRO}/dists/${CURRENT_MIRROR[2]}/${FILE}"
            curl -fsSL --create-dirs -o "${OUTPUT}" "${URL}"
        done
        local j
        for (( j=3; j<"${CURRENT_MIRROR_LEN}"; j++ )); do
            local DIST_FILES=("Contents-${ARCH}.gz" "${CURRENT_MIRROR[$j]}/Contents-${ARCH}.gz" "${CURRENT_MIRROR[$j]}/binary-${ARCH}/Packages.gz" "${CURRENT_MIRROR[$j]}/binary-${ARCH}/Packages.xz" "${CURRENT_MIRROR[$j]}/binary-${ARCH}/Release" "${CURRENT_MIRROR[$j]}/cnf/Commands-${ARCH}.xz")
            echo -n "${CURRENT_MIRROR[$j]} "
            for DIST_FILE in "${DIST_FILES[@]}"; do
                local URL="${CURRENT_MIRROR[1]}/dists/${CURRENT_MIRROR[2]}/${DIST_FILE}"
                local OUTPUT="${MIRROR_DIR}/${CURRENT_MIRROR_DISTRO}/dists/${CURRENT_MIRROR[2]}/${DIST_FILE}"
                local MD5SUM
                if MD5SUM=$(awk -v file="${DIST_FILE}" '$3 == file {print $1; rc=1; exit} END {exit !rc}' "${MIRROR_DIR}/${CURRENT_MIRROR_DISTRO}/dists/${CURRENT_MIRROR[2]}/Release"); then
                    if [ -f "${OUTPUT}" ]; then
                        local L_MD5SUM=$(md5sum "${OUTPUT}" 2>/dev/null | cut -d' ' -f1)
                        if [ "${MD5SUM}" != "${L_MD5SUM}" ]; then
                            rm ${OUTPUT}
                        fi
                    else
                        curl -fsSL --create-dirs -o "${OUTPUT}" "${URL}"
                    fi
                    local DL_MD5SUM=$(md5sum "${OUTPUT}" 2>/dev/null | cut -d' ' -f1)
                    if [ "${MD5SUM}" != "${DL_MD5SUM}" ]; then
                        echo "Error with file ${OUTPUT}" 1>&2
                        # TODO: something to try again
                    else
                        echo -e "${MD5SUM}\t${CURRENT_MIRROR_DISTRO}/dists/${CURRENT_MIRROR[2]}/${DIST_FILE}" >> "${TMP_DIR}/pool-MD5sums"
                    fi
                fi
            done
        done
        echo
    done
}

check_md5sums()
{
    if [ -f "${MIRROR_DIR}/MD5SUMS" ]; then
        (cd "${MIRROR_DIR}"; parallel --bar 'echo {} | md5sum --check --quiet' :::: MD5SUMS)
    else
        echo "${MIRROR_DIR}/MD5SUMS does not exist, please do a successful sync first" 1>&2
        exit 5
    fi
}

stage0()
{
    test_req
    include
    setup_dirs
    get_mirrors_from_list
}

stage1a()
{
    echo "Collecting package indices..."
    get_package_file_list

    echo "Checking local files..."
    get_local_file_list

stage1b()
{
    echo "Sorting list of files to download..."
    if [ $(wc -l "${TMP_DIR}/find-Sizes" | cut -d' ' -f1) = "0" ]; then
        cat "${TMP_DIR}/pool-Args" > "${TMP_DIR}/need-to-download"
    else
        awk -F'\t' 'FNR==NR {a[$2]=$1; next} !($3"/"$4 in a) || a[$3"/"$4] != $1' "${TMP_DIR}/find-Sizes" "${TMP_DIR}/pool-Args" > "${TMP_DIR}/need-to-download"
    fi

    local NUM_DOWNLOAD_FILES=$(wc -l "${TMP_DIR}/need-to-download" | cut -d' ' -f1 | tr -d '\n')
    if [ "${NUM_DOWNLOAD_FILES}" = "0" ]; then
        echo "No files to download"
    else
        echo "Downloading ${NUM_DOWNLOAD_FILES} files..."
        export MIRROR_DIR
        export -f get_file_from_repo
        parallel \
            --arg-file "${TMP_DIR}"/need-to-download \
            --colsep '\t' \
            --retries "${NUM_RETRIES}" \
            --joblog "${TMP_DIR}"/download-joblog \
            --bar \
            get_file_from_repo
    fi

}

stage1()
{
    stage1a
    stage1b
}

stage2()
{
    echo "Getting dist files..."
    get_release_files

    echo "Sorting list of files to remove..."
    awk -F'\t' 'FNR==NR {a[$3"/"$4]=$1; next} !($2 in a) || a[$2] != $1' "${TMP_DIR}/pool-Args" "${TMP_DIR}/find-Sizes" > "${TMP_DIR}/need-to-remove"

    local NUM_DELETE_FILES=$(wc -l "${TMP_DIR}/need-to-remove" | cut -d' ' -f1 | tr -d '\n')
    if [ "${NUM_DELETE_FILES}" = "0" ]; then
        echo "No files to remove"
    else
        echo "Removing ${NUM_DELETE_FILES} files..."
        export MIRROR_DIR
        parallel \
            --arg-file "${TMP_DIR}"/need-to-remove \
            --colsep '\t' \
            --retries "${NUM_RETRIES}" \
            --joblog "${TMP_DIR}"/remove-joblog \
            --bar \
            rm "${MIRROR_DIR}"/{2}
    fi
}

main()
{
    trap cleanup EXIT TERM HUP INT QUIT
    STAGES=(stage0)
    if [ "${1}" = "-h" ]; then
        STAGES=(usage)
    elif [ "${1}" = "-c" ]; then
        STAGES+=(check_md5sums)
    elif [ "${1}" = "-1" ]; then
        STAGES+=(stage1)
    elif [ "${1}" = "-2" ]; then
        STAGES+=(stage1a stage2)
    else
        STAGES+=(stage1 stage2)
    fi
    for STAGE in "${STAGES[@]}"; do
        "${STAGE}"
    done
}

main $@
